# Temporarily disabled due to hardware constraint, development moved to host

# services:
#   app:
#     build:
#       context: ./
#       target: dev
#     volumes:
#       - .:/app
#     command: npm run dev
#     ports:
#       - "3000:3000"
#       - "5555:5555" #expose port for prisma studio
